/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "auth.pb-c.h"
void   auth_request__init
                     (AuthRequest         *message)
{
  static const AuthRequest init_value = AUTH_REQUEST__INIT;
  *message = init_value;
}
size_t auth_request__get_packed_size
                     (const AuthRequest *message)
{
  assert(message->base.descriptor == &auth_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_request__pack
                     (const AuthRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_request__pack_to_buffer
                     (const AuthRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthRequest *
       auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthRequest *)
     protobuf_c_message_unpack (&auth_request__descriptor,
                                allocator, len, data);
}
void   auth_request__free_unpacked
                     (AuthRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor auth_request__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthRequest, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthRequest, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_request__field_indices_by_name[] = {
  1,   /* field[1] = password */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange auth_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor auth_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AuthRequest",
  "AuthRequest",
  "AuthRequest",
  "",
  sizeof(AuthRequest),
  2,
  auth_request__field_descriptors,
  auth_request__field_indices_by_name,
  1,  auth_request__number_ranges,
  (ProtobufCMessageInit) auth_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
