/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth.proto */

#ifndef PROTOBUF_C_auth_2eproto__INCLUDED
#define PROTOBUF_C_auth_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AuthRequest AuthRequest;


/* --- enums --- */


/* --- messages --- */

struct  _AuthRequest
{
  ProtobufCMessage base;
  char *username;
  char *password;
};
#define AUTH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&auth_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* AuthRequest methods */
void   auth_request__init
                     (AuthRequest         *message);
size_t auth_request__get_packed_size
                     (const AuthRequest   *message);
size_t auth_request__pack
                     (const AuthRequest   *message,
                      uint8_t             *out);
size_t auth_request__pack_to_buffer
                     (const AuthRequest   *message,
                      ProtobufCBuffer     *buffer);
AuthRequest *
       auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   auth_request__free_unpacked
                     (AuthRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AuthRequest_Closure)
                 (const AuthRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor auth_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_auth_2eproto__INCLUDED */
