/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nd_pam.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "nd_pam.pb-c.h"
void   pam_auth_req_info__init
                     (PamAuthReqInfo         *message)
{
  static const PamAuthReqInfo init_value = PAM_AUTH_REQ_INFO__INIT;
  *message = init_value;
}
size_t pam_auth_req_info__get_packed_size
                     (const PamAuthReqInfo *message)
{
  assert(message->base.descriptor == &pam_auth_req_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pam_auth_req_info__pack
                     (const PamAuthReqInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pam_auth_req_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pam_auth_req_info__pack_to_buffer
                     (const PamAuthReqInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pam_auth_req_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PamAuthReqInfo *
       pam_auth_req_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PamAuthReqInfo *)
     protobuf_c_message_unpack (&pam_auth_req_info__descriptor,
                                allocator, len, data);
}
void   pam_auth_req_info__free_unpacked
                     (PamAuthReqInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pam_auth_req_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pam_auth_req_info__field_descriptors[5] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PamAuthReqInfo, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userpwd",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PamAuthReqInfo, userpwd),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hiwarename",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PamAuthReqInfo, hiwarename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hiwarepwd",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PamAuthReqInfo, hiwarepwd),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remoteipaddr",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PamAuthReqInfo, remoteipaddr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pam_auth_req_info__field_indices_by_name[] = {
  2,   /* field[2] = hiwarename */
  3,   /* field[3] = hiwarepwd */
  4,   /* field[4] = remoteipaddr */
  0,   /* field[0] = username */
  1,   /* field[1] = userpwd */
};
static const ProtobufCIntRange pam_auth_req_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor pam_auth_req_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PamAuthReqInfo",
  "PamAuthReqInfo",
  "PamAuthReqInfo",
  "",
  sizeof(PamAuthReqInfo),
  5,
  pam_auth_req_info__field_descriptors,
  pam_auth_req_info__field_indices_by_name,
  1,  pam_auth_req_info__number_ranges,
  (ProtobufCMessageInit) pam_auth_req_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
