/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nd_pam.proto */

#ifndef PROTOBUF_C_nd_5fpam_2eproto__INCLUDED
#define PROTOBUF_C_nd_5fpam_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PamAuthReqInfo PamAuthReqInfo;


/* --- enums --- */


/* --- messages --- */

struct  _PamAuthReqInfo
{
  ProtobufCMessage base;
  char *username;
  char *userpwd;
  char *hiwarename;
  char *hiwarepwd;
  char *remoteipaddr;
};
#define PAM_AUTH_REQ_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pam_auth_req_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* PamAuthReqInfo methods */
void   pam_auth_req_info__init
                     (PamAuthReqInfo         *message);
size_t pam_auth_req_info__get_packed_size
                     (const PamAuthReqInfo   *message);
size_t pam_auth_req_info__pack
                     (const PamAuthReqInfo   *message,
                      uint8_t             *out);
size_t pam_auth_req_info__pack_to_buffer
                     (const PamAuthReqInfo   *message,
                      ProtobufCBuffer     *buffer);
PamAuthReqInfo *
       pam_auth_req_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pam_auth_req_info__free_unpacked
                     (PamAuthReqInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PamAuthReqInfo_Closure)
                 (const PamAuthReqInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pam_auth_req_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_nd_5fpam_2eproto__INCLUDED */
